(in-package :nominal)

(defparameter +animals+
  '((aardvark)
    (abyssinian)
    (addax)
    (adelie penguin)
    (affenpinscher)
    (afghan hound)
    (african bullfrog)
    (african bush elephant)
    (african civet)
    (african clawed frog)
    (african forest elephant)
    (african palm civet)
    (african penguin)
    (african tree toad)
    (african wild dog)
    (aidi)
    (ainu)
    (airedale terrier)
    (airedoodle)
    (akbash)
    (akita)
    (akita shepherd)
    (alabai)
    (alaskan husky)
    (alaskan klee kai)
    (alaskan malamute)
    (alaskan shepherd)
    (albacore tuna)
    (albatross)
    (aldabra giant tortoise)
    (alligator)
    (alligator gar)
    (alpaca)
    (alpine dachsbracke)
    (alpine goat)
    (alusky)
    (amazon river dolphin)
    (american alsatian)
    (american bulldog)
    (american cocker spaniel)
    (american cockroach)
    (american coonhound)
    (american eskimo dog)
    (american foxhound)
    (american hairless terrier)
    (american leopard hound)
    (american pit bull terrier)
    (american pygmy goat)
    (american robin)
    (american staffordshire terrier)
    (american toad)
    (american water spaniel)
    (amur leopard)
    (anatolian shepherd dog)
    (anchovies)
    (angelfish)
    (anglerfish)
    (angora goat)
    (ant)
    (antarctic scale worm)
    (anteater)
    (antelope)
    (appenzeller dog)
    (apple head chihuahua)
    (arapaima)
    (arctic fox)
    (arctic hare)
    (arctic wolf)
    (arizona bark scorpion)
    (armadillo)
    (armyworm)
    (asian elephant)
    (asian giant hornet)
    (asian palm civet)
    (asiatic black bear)
    (aurochs)
    (aussiedoodle)
    (aussiedor)
    (australian bulldog)
    (australian cattle dog)
    (australian gecko)
    (australian kelpie dog)
    (australian labradoodle)
    (australian mist)
    (australian retriever)
    (australian shepherd)
    (australian terrier)
    (avocet)
    (axolotl)
    (aye aye)
    (babirusa)
    (baboon)
    (bactrian camel)
    (badger)
    (baiji)
    (baleen whale)
    (balinese)
    (balkan lynx)
    (banana spider)
    (banded palm civet)
    (bandicoot)
    (banjo catfish)
    (barb)
    (barbet)
    (barn owl)
    (barn swallow)
    (barnacle)
    (barracuda)
    (barramundi fish)
    (barred owl)
    (basenji dog)
    (basking shark)
    (bassador)
    (basset fauve de bretagne)
    (basset hound)
    (bassetoodle)
    (bat)
    (bavarian mountain hound)
    (bea-tzu)
    (beabull)
    (beagador)
    (beagle)
    (beagle shepherd)
    (beaglier)
    (beago)
    (bear)
    (bearded collie)
    (bearded dragon)
    (beaski)
    (beauceron)
    (beaver)
    (bedlington terrier)
    (beefalo)
    (beetle)
    (belgian shepherd)
    (belgian tervuren)
    (beluga sturgeon)
    (bengal tiger)
    (bergamasco)
    (berger picard)
    (bernedoodle)
    (bernese mountain dog)
    (bernese shepherd)
    (bichir)
    (bichon frise)
    (bichpoo)
    (biewer terrier)
    (bighorn sheep)
    (bilby)
    (binturong)
    (bird)
    (bird of paradise)
    (birman)
    (bison)
    (black and tan coonhound)
    (black marlin)
    (black rhinoceros)
    (black russian terrier)
    (black wasp)
    (black widow spider)
    (black-footed ferret)
    (blister beetle)
    (blobfish)
    (bloodhound)
    (blue grosbeak)
    (blue iguana)
    (blue jay)
    (blue lacy dog)
    (blue picardy spaniel)
    (blue shark)
    (blue whale)
    (blue-ringed octopus)
    (bluefin tuna)
    (bluetick coonhound)
    (bobcat)
    (boggle)
    (boglen terrier)
    (bolognese dog)
    (bombay)
    (bongo)
    (bonito fish)
    (bonnethead shark)
    (bonobo)
    (booby)
    (borador)
    (border collie)
    (border terrier)
    (bordoodle)
    (borkie)
    (bornean orang-utan)
    (borneo elephant)
    (boston terrier)
    (bottlenose dolphin)
    (bouvier des flandres)
    (bowfin)
    (bowhead whale)
    (box turtle)
    (boxador)
    (boxer dog)
    (boxerdoodle)
    (boxsky)
    (boxweiler)
    (boykin spaniel)
    (brazilian terrier)
    (british timber)
    (brittany)
    (brookesia micra)
    (brown bear)
    (brown hyena)
    (brug)
    (brussels griffon)
    (budgerigar)
    (buffalo)
    (bull shark)
    (bull terrier)
    (bulldog)
    (bullfrog)
    (bullmastiff)
    (bumblebee)
    (burmese)
    (burmese python)
    (burrowing frog)
    (bush baby)
    (butterfly)
    (butterfly fish)
    (caiman)
    (caiman lizard)
    (cairn terrier)
    (camel)
    (camel cricket)
    (camel spider)
    (canaan dog)
    (canada lynx)
    (canadian eskimo dog)
    (canadian horse)
    (cane corso)
    (cape lion)
    (capybara)
    (caracal)
    (caribou)
    (carolina dog)
    (carolina parakeet)
    (carp)
    (carpenter ant)
    (cashmere goat)
    (cassowary)
    (cat)
    (catahoula leopard)
    (catalan sheepdog)
    (caterpillar)
    (catfish)
    (cava tzu)
    (cavador)
    (cavalier king charles spaniel)
    (cavapoo)
    (centipede)
    (cesky fousek)
    (cesky terrier)
    (chameleon)
    (chamois)
    (cheagle)
    (cheetah)
    (chesapeake bay retriever)
    (chickadee)
    (chicken)
    (chihuahua)
    (chimaera)
    (chimpanzee)
    (chinchilla)
    (chinese alligator)
    (chinese crested dog)
    (chinese geese)
    (chinese paddlefish)
    (chinese shar-pei)
    (chinook)
    (chinstrap penguin)
    (chipmunk)
    (chipoo)
    (chiweenie)
    (chorkie)
    (chow chow)
    (chow shepherd)
    (christmas island red crab)
    (cicada)
    (cichlid)
    (clouded leopard)
    (clownfish)
    (clumber spaniel)
    (coati)
    (cockalier)
    (cockapoo)
    (cockatoo)
    (cockroach)
    (codfish)
    (coelacanth)
    (collared peccary)
    (collie)
    (colossal squid)
    (common buzzard)
    (common frog)
    (common house spider)
    (common loon)
    (common raven)
    (common toad)
    (cookiecutter shark)
    (cooper’s hawk)
    (coral)
    (corgidor)
    (corgipoo)
    (corkie)
    (corman shepherd)
    (coton de tulear)
    (cotton-top tamarin)
    (cougar)
    (cow)
    (coyote)
    (crab)
    (crab spider)
    (crab-eating macaque)
    (crabeater seal)
    (crane)
    (crappie fish)
    (crested penguin)
    (crocodile)
    (cross fox)
    (cross river gorilla)
    (curly coated retriever)
    (cuscus)
    (cuttlefish)
    (czechoslovakian wolfdog)
    (dachsador)
    (dachshund)
    (dalmadoodle)
    (dalmador)
    (dalmatian)
    (dapple dachshund)
    (darwin’s fox)
    (darwin’s frog)
    (deer)
    (deer head chihuahua)
    (desert locust)
    (desert rain frog)
    (desert tortoise)
    (deutsche bracke)
    (dhole)
    (dik-dik)
    (dingo)
    (discus)
    (doberman pinscher)
    (dodo)
    (dog)
    (dogo argentino)
    (dogue de bordeaux)
    (dolphin)
    (donkey)
    (dorgi)
    (dorkie)
    (dormouse)
    (double doodle)
    (doxiepoo)
    (doxle)
    (draco volans)
    (dragonfish)
    (dragonfly)
    (drever)
    (drum fish)
    (duck)
    (dugong)
    (dung beetle)
    (dunker)
    (dusky dolphin)
    (dwarf crocodile)
    (eagle)
    (earwig)
    (eastern bluebird)
    (eastern fence lizard)
    (eastern gorilla)
    (eastern lowland gorilla)
    (eastern phoebe)
    (echidna)
    (edible frog)
    (eel)
    (egyptian mau)
    (electric eel)
    (elephant)
    (elephant seal)
    (elephant shrew)
    (elk)
    (emperor penguin)
    (emperor tamarin)
    (emu)
    (english cocker spaniel)
    (english cream golden retriever)
    (english foxhound)
    (english pointer)
    (english setter)
    (english shepherd)
    (english springer spaniel)
    (entlebucher mountain dog)
    (epagneul pont audemer)
    (ermine)
    (eskimo dog)
    (eskipoo)
    (estrela mountain dog)
    (falcon)
    (fallow deer)
    (false killer whale)
    (false widow spider)
    (fangtooth)
    (feist)
    (fennec fox)
    (ferret)
    (ferruginous hawk)
    (fiddler crab)
    (field spaniel)
    (fila brasileiro)
    (fin whale)
    (finnish spitz)
    (fire salamander)
    (fire-bellied toad)
    (fish)
    (fisher cat)
    (fishing cat)
    (flamingo)
    (flat-coated retriever)
    (florida gar)
    (florida panther)
    (flounder)
    (flowerhorn fish)
    (fluke fish)
    (fly)
    (flying fish)
    (flying lemur)
    (flying squirrel)
    (formosan mountain dog)
    (fossa)
    (fox)
    (fox terrier)
    (french bulldog)
    (frenchton)
    (frengle)
    (frigatebird)
    (frilled lizard)
    (frilled shark)
    (frog)
    (frogfish)
    (fruit bat)
    (fur seal)
    (galapagos penguin)
    (galapagos tortoise)
    (gar)
    (garden eel)
    (gecko)
    (genet)
    (gentoo penguin)
    (geoffroys tamarin)
    (gerberian shepsky)
    (gerbil)
    (german pinscher)
    (german shepherd guide)
    (german sheppit)
    (german sheprador)
    (german shorthaired pointer)
    (german spitz)
    (gharial)
    (ghost crab)
    (giant african land snail)
    (giant armadillo)
    (giant clam)
    (giant panda bear)
    (giant salamander)
    (giant schnauzer)
    (giant schnoodle)
    (gibbon)
    (gila monster)
    (giraffe)
    (glass frog)
    (glass lizard)
    (glechon)
    (glen of imaal terrier)
    (glow worm)
    (goat)
    (goberian)
    (goblin shark)
    (goldador)
    (golden dox)
    (golden lion tamarin)
    (golden masked owl)
    (golden newfie)
    (golden oriole)
    (golden pyrenees)
    (golden retriever)
    (golden saint)
    (golden shepherd)
    (golden-crowned flying fox)
    (goldendoodle)
    (goliath frog)
    (goose)
    (gopher)
    (gopher tortoise)
    (gordon setter)
    (gorilla)
    (gouldian finch)
    (grasshopper)
    (grasshopper mouse)
    (gray fox)
    (gray tree frog)
    (great blue heron)
    (great dane)
    (great danoodle)
    (great pyrenees)
    (great white shark)
    (greater swiss mountain dog)
    (green anole)
    (green bee-eater)
    (green frog)
    (green tree frog)
    (greenland dog)
    (greenland shark)
    (grey mouse lemur)
    (grey reef shark)
    (grey seal)
    (greyhound)
    (griffonshire)
    (grizzly bear)
    (groenendael)
    (groundhog)
    (grouse)
    (guinea fowl)
    (guinea pig)
    (guppy)
    (haddock)
    (hagfish)
    (hammerhead shark)
    (hamster)
    (harbor seal)
    (hardhead catfish)
    (hare)
    (harp seal)
    (harpy eagle)
    (harrier)
    (havanese)
    (havapoo)
    (havashire)
    (hawaiian crow)
    (hawaiian monk seal)
    (hedgehog)
    (hercules beetle)
    (hermit crab)
    (heron)
    (herring)
    (highland cattle)
    (himalayan)
    (hippopotamus)
    (hoary bat)
    (hokkaido)
    (honduran white bat)
    (honey badger)
    (honey bee)
    (hooded seal)
    (hoopoe)
    (horgi)
    (horn shark)
    (hornbill)
    (horned frog)
    (horned lizard)
    (horse)
    (horsefly)
    (horseshoe crab)
    (house finch)
    (house wren)
    (howler monkey)
    (human)
    (humboldt penguin)
    (humboldt squid)
    (hummingbird)
    (humpback whale)
    (huntaway)
    (huntsman spider)
    (huskador)
    (husky jack)
    (huskydoodle)
    (hyena)
    (ibex)
    (ibis)
    (ibizan hound)
    (icelandic sheepdog)
    (iguana)
    (immortal jellyfish)
    (impala)
    (imperial moth)
    (indian elephant)
    (indian giant squirrel)
    (indian palm squirrel)
    (indian rhinoceros)
    (indian star tortoise)
    (indochinese tiger)
    (indri)
    (insects)
    (irish doodle)
    (irish setter)
    (irish terrier)
    (irish water spaniel)
    (irish wolfhound)
    (italian greyhound)
    (ivory-billed woodpecker)
    (jack russell)
    (jackabee)
    (jackal)
    (jackson’s chameleon)
    (jaguar)
    (jaguarundi cat)
    (japanese beetle)
    (japanese chin)
    (japanese macaque)
    (japanese spitz)
    (japanese squirrel)
    (japanese terrier)
    (javan rhinoceros)
    (javanese)
    (jellyfish)
    (jerboa)
    (kai ken)
    (kakapo)
    (kangal)
    (kangaroo)
    (kangaroo rat)
    (keel-billed toucan)
    (keeshond)
    (kerry blue terrier)
    (key deer)
    (kiko goat)
    (killer whale)
    (kinder goat)
    (king cobra)
    (king crab)
    (king penguin)
    (king shepherd)
    (kingfisher)
    (kinkajou)
    (kishu)
    (kiwi)
    (koala)
    (kodkod)
    (koi fish)
    (komodo dragon)
    (kooikerhondje)
    (kookaburra)
    (koolie)
    (krill)
    (kudu)
    (kuvasz)
    (labahoula)
    (labmaraner)
    (labradane)
    (labradoodle)
    (labrador retriever)
    (labraheeler)
    (ladybug)
    (lakeland terrier)
    (lamancha goat)
    (lamprey)
    (lancashire heeler)
    (lapponian herder)
    (leaf-tailed gecko)
    (lemming)
    (lemur)
    (leonberger)
    (leopard)
    (leopard cat)
    (leopard frog)
    (leopard seal)
    (leopard tortoise)
    (lhasa apso)
    (lhasapoo)
    (liger)
    (lion)
    (lion’s mane jellyfish)
    (lionfish)
    (little brown bat)
    (little penguin)
    (lizard)
    (llama)
    (loach)
    (lobster)
    (locust)
    (long-eared owl)
    (long-haired rottweiler)
    (longnose gar)
    (lorikeet)
    (lowchen)
    (lungfish)
    (lynx)
    (macaroni penguin)
    (macaw)
    (mackenzie wolf)
    (magellanic penguin)
    (magpie)
    (maine coon)
    (malayan civet)
    (malayan tiger)
    (mallard)
    (malteagle)
    (maltese)
    (maltese shih tzu)
    (maltipoo)
    (man of war jellyfish)
    (manatee)
    (manchester terrier)
    (mandrill)
    (maned wolf)
    (manta ray)
    (mantella frog)
    (marabou stork)
    (marble fox)
    (marine iguana)
    (marine toad)
    (markhor)
    (marmot)
    (marsh frog)
    (masked palm civet)
    (mastador)
    (mastiff)
    (mayfly)
    (meagle)
    (mealybug)
    (meerkat)
    (megalodon)
    (megamouth shark)
    (mekong giant catfish)
    (mexican alligator lizard)
    (mexican free-tailed bat)
    (mexican mole lizard)
    (miki)
    (milkfish)
    (millipede)
    (mini labradoodle)
    (miniature bull terrier)
    (miniature husky)
    (miniature pinscher)
    (mink)
    (minke whale)
    (mole)
    (mole cricket)
    (molly)
    (monarch butterfly)
    (mongoose)
    (mongrel)
    (monitor lizard)
    (monkey)
    (monkfish)
    (monte iberia eleuth)
    (moorhen)
    (moose)
    (moray eel)
    (morkie)
    (moscow watchdog)
    (moth)
    (mountain bluebird)
    (mountain cur)
    (mountain feist)
    (mountain gorilla)
    (mountain lion)
    (mourning dove)
    (mouse)
    (mudi)
    (mudpuppy)
    (mule)
    (muntjac)
    (muskox)
    (muskrat)
    (myna bird)
    (naked mole rat)
    (narwhal)
    (neanderthal)
    (neapolitan mastiff)
    (newfoundland)
    (newfypoo)
    (newt)
    (nigerian goat)
    (nightingale)
    (nile crocodile)
    (no see ums)
    (norfolk terrier)
    (north american black bear)
    (northern alligator lizard)
    (northern cardinal)
    (northern fur seal)
    (northern inuit dog)
    (norwegian buhund)
    (norwegian elkhound)
    (norwegian forest)
    (norwegian lundehund)
    (norwich terrier)
    (nova scotia duck tolling retriever)
    (nubian goat)
    (numbat)
    (nurse shark)
    (ocelot)
    (octopus)
    (okapi)
    (old english sheepdog)
    (olm)
    (opossum)
    (orang-utan)
    (orb weaver)
    (ostrich)
    (otter)
    (otterhound)
    (oyster)
    (paddlefish)
    (pademelon)
    (painted turtle)
    (pangolin)
    (panther)
    (papillon)
    (parakeet)
    (parrot)
    (parrotlet)
    (parson russell terrier)
    (patas monkey)
    (patterdale terrier)
    (peacock)
    (peacock butterfly)
    (peacock spider)
    (peagle)
    (peekapoo)
    (pekingese)
    (pelican)
    (pembroke welsh corgi)
    (penguin)
    (pere davids deer)
    (peregrine falcon)
    (perro de presa canario)
    (persian)
    (peruvian inca orchid)
    (petit basset griffon vendéen)
    (petite goldendoodle)
    (pheasant)
    (pied tamarin)
    (pig)
    (pigeon)
    (pika)
    (pike fish)
    (pileated woodpecker)
    (pine marten)
    (pink fairy armadillo)
    (piranha)
    (pitador)
    (pitsky)
    (platypus)
    (pocket beagle)
    (pocket pitbull)
    (pointer)
    (poison dart frog)
    (polar bear)
    (polish lowland sheepdog)
    (polyphemus moth)
    (pomapoo)
    (pomchi)
    (pomeagle)
    (pomeranian)
    (pomsky)
    (pond skater)
    (poochon)
    (poodle)
    (poogle)
    (pool frog)
    (porbeagle shark)
    (porcupine)
    (porpoise)
    (possum)
    (potoroo)
    (prairie dog)
    (prairie rattlesnake)
    (prawn)
    (proboscis monkey)
    (pronghorn)
    (pudelpointer)
    (pufferfish)
    (puffin)
    (pug)
    (pugapoo)
    (puggle)
    (pugshire)
    (puma)
    (pumi)
    (purple emperor butterfly)
    (purple finch)
    (puss moth)
    (pygmy hippopotamus)
    (pygmy marmoset)
    (pygora goat)
    (pyrador)
    (pyredoodle)
    (quagga)
    (quail)
    (quetzal)
    (quokka)
    (quoll)
    (rabbit)
    (raccoon)
    (raccoon dog)
    (radiated tortoise)
    (ragdoll)
    (raggle)
    (rat)
    (rat terrier)
    (rattlesnake)
    (red finch)
    (red fox)
    (red knee tarantula)
    (red panda)
    (red squirrel)
    (red wolf)
    (red-handed tamarin)
    (red-winged blackbird)
    (redback spider)
    (redbone coonhound)
    (reef shark)
    (reindeer)
    (rhinoceros)
    (river turtle)
    (robin)
    (rock crab)
    (rock hyrax)
    (rockfish)
    (rockhopper penguin)
    (rodents)
    (roe deer)
    (rose-breasted grosbeak)
    (roseate spoonbill)
    (rottsky)
    (rottweiler)
    (royal penguin)
    (ruby-throated hummingbird)
    (russell terrier)
    (russian bear dog)
    (russian blue)
    (russian tortoise)
    (saanen goat)
    (saarloos wolfdog)
    (saber-toothed tiger)
    (sable)
    (saiga)
    (saint berdoodle)
    (saint bernard)
    (saint shepherd)
    (salamander)
    (salmon)
    (salmon shark)
    (saluki)
    (samoyed)
    (sand lizard)
    (sand tiger shark)
    (saola)
    (sardines)
    (satanic leaf-tailed gecko)
    (savanna goat)
    (sawfish)
    (scarlet macaw)
    (schipperke)
    (schneagle)
    (schnoodle)
    (scimitar-horned oryx)
    (scorpion)
    (scorpion fish)
    (scottish terrier)
    (sea anemone)
    (sea dragon)
    (sea lion)
    (sea otter)
    (sea slug)
    (sea squirt)
    (sea turtle)
    (sea urchin)
    (seahorse)
    (seal)
    (sealyham terrier)
    (sei whale)
    (senegal parrot)
    (serval)
    (shark)
    (sharp-tailed snake)
    (sheep)
    (sheepadoodle)
    (shepadoodle)
    (shepkita)
    (shepweiler)
    (shiba inu)
    (shih poo)
    (shih tzu)
    (shoebill stork)
    (shollie)
    (shrimp)
    (siamese)
    (siamese fighting fish)
    (siberian)
    (siberian husky)
    (siberian retriever)
    (siberian tiger)
    (siberpoo)
    (silkie chicken)
    (silky terrier)
    (silver dollar)
    (silver labrador)
    (sixgill shark)
    (skate fish)
    (skink lizard)
    (skipjack tuna)
    (skunk)
    (skye terrier)
    (sleeper shark)
    (sloth)
    (slow worm)
    (slug)
    (smooth fox terrier)
    (snail)
    (snake)
    (snapping turtle)
    (snorkie)
    (snow leopard)
    (snowshoe)
    (snowshoe hare)
    (snowy owl)
    (somali)
    (south china tiger)
    (spadefoot toad)
    (spanador)
    (spanish goat)
    (spanish mastiff)
    (sparrow)
    (spectacled bear)
    (sperm whale)
    (spider monkey)
    (spider wasp)
    (spinner shark)
    (spinone italiano)
    (spiny dogfish)
    (spiny hill turtle)
    (spixs macaw)
    (sponge)
    (spotted gar)
    (spotted lanternfly)
    (springador)
    (springbok)
    (springerdoodle)
    (squid)
    (squirrel)
    (squirrel monkey)
    (squirrelfish)
    (sri lankan elephant)
    (stabyhoun)
    (staffordshire bull terrier)
    (stag beetle)
    (standard schnauzer)
    (star-nosed mole)
    (starfish)
    (steller’s sea cow)
    (stick insect)
    (stingray)
    (stoat)
    (stone crab)
    (striped hyena)
    (striped rocket frog)
    (sturgeon)
    (sucker fish)
    (sugar glider)
    (sulcata tortoise)
    (sumatran elephant)
    (sumatran orang-utan)
    (sumatran rhinoceros)
    (sumatran tiger)
    (sun bear)
    (swai fish)
    (swan)
    (swedish vallhund)
    (syrian hamster)
    (taco terrier)
    (tamaskan)
    (tang)
    (tapanuli orang-utan)
    (tapir)
    (tarantula hawk)
    (tarpon)
    (tarsier)
    (tasmanian devil)
    (tasmanian tiger)
    (tawny owl)
    (teddy bear hamster)
    (teddy roosevelt terrier)
    (tenterfield terrier)
    (termite)
    (terrier)
    (tetra)
    (texas heeler)
    (thai ridgeback)
    (thorny devil)
    (thrush)
    (tibetan fox)
    (tibetan mastiff)
    (tibetan spaniel)
    (tibetan terrier)
    (tiffany)
    (tiger)
    (tiger beetle)
    (tiger moth)
    (tiger salamander)
    (tiger shark)
    (toadfish)
    (torkie)
    (tortoise)
    (toucan)
    (toy fox terrier)
    (toy poodle)
    (transylvanian hound)
    (tree frog)
    (tree kangaroo)
    (tree swallow)
    (treeing tennessee brindle)
    (treeing walker coonhound)
    (tropicbird)
    (tsetse fly)
    (tuatara)
    (tuna)
    (turkey)
    (turkish angora)
    (turtles)
    (uakari)
    (uguisu)
    (umbrellabird)
    (utonagan)
    (vampire bat)
    (vampire squid)
    (vaquita)
    (vervet monkey)
    (vinegaroon)
    (virgin islands dwarf gecko)
    (vizsla)
    (volpino italiano)
    (vulture)
    (walking catfish)
    (wallaby)
    (walleye fish)
    (walrus)
    (wandering albatross)
    (warthog)
    (wasp)
    (water buffalo)
    (water dragon)
    (water vole)
    (weasel)
    (weimaraner)
    (weimardoodle)
    (welsh corgi)
    (welsh terrier)
    (west highland terrier)
    (western gorilla)
    (western lowland gorilla)
    (westiepoo)
    (whale shark)
    (wheaten terrier)
    (whippet)
    (white butterfly)
    (white rhinoceros)
    (white tiger)
    (white-faced capuchin)
    (white-tail deer)
    (white-tailed eagle)
    (whoodle)
    (whooping crane)
    (wild boar)
    (wildebeest)
    (willow warbler)
    (wire fox terrier)
    (wirehaired pointing griffon)
    (wolf)
    (wolf eel)
    (wolf spider)
    (wolffish)
    (wolverine)
    (wombat)
    (wood bison)
    (wood frog)
    (wood turtle)
    (woodlouse)
    (woodlouse spider)
    (woodpecker)
    (woolly mammoth)
    (woolly monkey)
    (wrasse)
    (wyoming toad)
    (x-ray tetra)
    (xerus)
    (xoloitzcuintli)
    (yak)
    (yakutian laika)
    (yellow sac spider)
    (yellow-eyed penguin)
    (yellowfin tuna)
    (yeti crab)
    (yoranian)
    (yorkie bichon)
    (yorkie poo)
    (yorkshire terrier)
    (zebra)
    (zebra finch)
    (zebra mussels)
    (zebra pleco)
    (zebra shark)
    (zebu)
    (zonkey)
    (zorse)
    (zuchon)))

(defun animal-as-syms ()
  (rand-nth +animals+))

(defun animal-as-str ()
  (string-downcase
   (format nil "~{~a~^ ~}" (animal-as-syms))))
